/*
 * generated by Xtext 2.32.0
 */
package com.itemis.mbse4me.dsls.validation;

import org.eclipse.xtext.validation.Check;

import com.itemis.mbse4me.dsls.erModel.Assembly;
import com.itemis.mbse4me.dsls.erModel.Component;
import com.itemis.mbse4me.dsls.erModel.ErModelPackage;
import com.itemis.mbse4me.dsls.erModel.Product;
import com.itemis.mbse4me.dsls.utils.UnicodeConstants;

/**
 * This class contains custom validation rules.
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ErModelValidator extends AbstractErModelValidator {

	@Check
	public void checkComponentHasValidPrice(Component component) {
		if (!component.getPrice().contains(UnicodeConstants.EURO_SYMBOL)) {
			error("Price has no currency!", ErModelPackage.Literals.COMPONENT__PRICE, ErModelIssueCodes.COMPONENT_MISSING_CURRENCY);
		}
	}

	@Check
	public void checkAssemblyHasAtLeastOneComponent(Assembly assembly) {
		if (assembly.getComponentUsages().isEmpty()) {
			warning("Assembly uses no components", ErModelPackage.Literals.ASSEMBLY__COMPONENT_USAGES, ErModelIssueCodes.ASSEMBLY_HAS_NO_COMPONENT);
		}
	}

	@Check
	public void checkProductHasAtLeastOneAssembly(Product product) {
		if (product.getAssemblyUsages().isEmpty()) {
			warning("Product uses no assemblies", ErModelPackage.Literals.PRODUCT__ASSEMBLY_USAGES, ErModelIssueCodes.PRODUCT_HAS_NO_ASSEMBLY);
		}
	}

}
