/*
 * generated by Xtext 2.32.0
 */
package com.itemis.mbse4me.dsls.ui.labeling;

import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class ErModelDescriptionLabelProvider extends DefaultDescriptionLabelProvider {

	@Override
	public String image(IEObjectDescription element) {
		return element.getEClass().getName() + ".png";
	}
}
