/*
 * generated by Xtext 2.32.0
 */
package com.itemis.mbse4me.dsls.ui.labeling;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;
import com.itemis.mbse4me.dsls.erModel.Assembly;
import com.itemis.mbse4me.dsls.erModel.Product;
import com.itemis.mbse4me.dsls.ui.utils.ErModelUiUtils;

/**
 * Provides labels for EObjects.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class ErModelLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public ErModelLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	Object text(Product product) {
		int assembliesCount = product.getAssemblyUsages().size();
		String text = product.getName() + " - " + assembliesCount + " Assembl";
		if (assembliesCount > 1) {
			text += "ies";
		} else {
			text += "y";
		}
		return ErModelUiUtils.style(text);
	}

	Object text(Assembly assembly) {
		int componentCount = assembly.getComponentUsages().size();
		String text = assembly.getName() + " - " + componentCount + " Component";
		if (componentCount > 1) {
			text += "s";
		}
		return ErModelUiUtils.style(text);
	}

	Object image(EObject eObject) {
		return eObject.eClass().getName() + ".png";
	}
}
