/*
 * generated by Xtext 2.32.0
 */
package com.itemis.mbse4me.dsls;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ErModelStandaloneSetup extends ErModelStandaloneSetupGenerated {

	public static void doSetup() {
		new ErModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
