/*
 * generated by Xtext 2.32.0
 */
package com.itemis.mbse4me.dsls;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RequirementRuntimeModule extends AbstractRequirementRuntimeModule {
}
