/*
 * generated by Xtext 2.32.0
 */
package com.itemis.mbse4me.dsls.ui.quickfix;

import org.eclipse.xtext.ui.editor.model.edit.IMultiModification;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;

import com.itemis.mbse4me.dsls.erModel.Component;
import com.itemis.mbse4me.dsls.utils.UnicodeConstants;
import com.itemis.mbse4me.dsls.validation.ErModelIssueCodes;

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class ErModelQuickfixProvider extends DefaultQuickfixProvider {

	@Fix(ErModelIssueCodes.COMPONENT_MISSING_CURRENCY)
	public void capitalizeName(final Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.acceptMulti(issue, "Add Euro currency", "Add Euro currency", "upcase.png", new IMultiModification<Component>() {

			@Override
			public void apply(Component component) {
				component.setPrice(component.getPrice() + UnicodeConstants.EURO_SYMBOL);
			}
		});
	}

}
