/*
 * generated by Xtext 2.32.0
 */
package com.itemis.mbse4me.dsls.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.doubleClicking.DoubleClickStrategyProvider;
import org.eclipse.xtext.ui.refactoring.IRenameStrategy;

import com.itemis.mbse4me.dsls.ui.doubleclicking.ErModelDoubleClickStrategyProvider;
import com.itemis.mbse4me.dsls.ui.renaming.ErModelRenameStrategy;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ErModelUiModule extends AbstractErModelUiModule {

	public ErModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends DoubleClickStrategyProvider> bindDoubleClickStrategyProvider() {
		return ErModelDoubleClickStrategyProvider.class;
	}

	@Override
	public Class<? extends IRenameStrategy> bindIRenameStrategy() {
		return ErModelRenameStrategy.class;
	}
}
