/*
 * generated by Xtext 2.32.0
 */
package com.itemis.mbse4me.dsls.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

import com.itemis.mbse4me.dsls.ui.highlighting.MultilineStringAwareHighlightingConfiguration;
import com.itemis.mbse4me.dsls.ui.highlighting.MultilineStringAwareSemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RequirementUiModule extends AbstractRequirementUiModule {

	public RequirementUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return MultilineStringAwareHighlightingConfiguration.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return MultilineStringAwareSemanticHighlightingCalculator.class;
	}

//	public Class<? extends ITokenTypeToPartitionTypeMapper> bindITokenTypeToPartitionTypeMapper() {
//		return MultilineStringAwareTerminalsTokenTypeToPartitionMapper.class;
//	}
}
