/*
 * generated by Xtext 2.32.0
 */
package com.itemis.mbse4me.dsls.ui.wizard;

import org.eclipse.osgi.util.NLS;

public class Messages extends NLS {
	private static final String BUNDLE_NAME = "com.itemis.mbse4me.dsls.ui.wizard.messages"; //$NON-NLS-1$
	
	public static String HelloWorldProject_Label;
	public static String HelloWorldProject_Description;
	public static String ProjectImportedFromExcel_Label;
	public static String ProjectImportedFromExcel_Description;
	
	static {
	// initialize resource bundle
	NLS.initializeMessages(BUNDLE_NAME, Messages.class);
	}
	
	private Messages() {
	}
}
