/*
 * generated by Xtext 2.32.0
 */
package com.itemis.mbse4me.dsls.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.itemis.mbse4me.dsls.ErModelRuntimeModule;
import com.itemis.mbse4me.dsls.ErModelStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ErModelIdeSetup extends ErModelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ErModelRuntimeModule(), new ErModelIdeModule()));
	}
	
}
