/*
 * generated by Xtext 2.32.0
 */
package com.itemis.mbse4me.dsls.tests

import com.google.inject.Inject
import com.itemis.mbse4me.dsls.requirement.Requirement
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

import static com.itemis.mbse4me.dsls.tests.utils.TestUtils.c

@ExtendWith(InjectionExtension)
@InjectWith(RequirementInjectorProvider)
class RequirementParsingTest {

	@Inject extension ParseHelper<Requirement>
	@Inject extension ValidationTestHelper

	@Test def test001() {
		'''
			Number: "1.1.1"
			Text: «c»
				Requirement text.
			«c»
		'''.hasNoErrors
	}

	private def hasNoErrors(CharSequence text) {
		text.parse.assertNoErrors
	}
}

